// Texts shown to the player. To add a language copy one block under a new code and translate the values.
const TEXTS = {
    pl: {
        languageName: 'Polski',
        language: 'Język',
        title: 'MROŹNE OSTRZE',
        loading: 'Ładowanie...',
        rotate: 'Obróć telefon poziomo',
        keysMove: 'STRZAŁKI - ruch, skok i zeskok &nbsp; SHIFT - unik',
        keysUse: 'SPACJA - użyj, przytrzymaj z łukiem &nbsp; 1-9 - wybór',
        keysSkills: 'X - mroźne cięcie &nbsp; C - lodowa tarcza &nbsp; Q - umiejętność z talentów',
        keysMenu: 'I - ekwipunek &nbsp; T - talenty &nbsp; E - kupiec, tablica zadań &nbsp; F - pełny ekran &nbsp; H - tryb foto &nbsp; O - ustawienia &nbsp; ESC - pauza',
        hintTouch: 'Przytrzymaj UŻYJ, by strzelić z łuku',
        goal: 'Przejdź Zimowy Las, Lodową Jaskinię i Ruiny Zamku',
        storyIntro: 'Zimowa Klątwa spowiła krainę wiecznym mrozem. Odnajdź jej źródło i połóż jej kres.',
        level: 'Poziom {level}',
        levelUp: 'AWANS! Poziom {level}',
        tap: 'DOTKNIJ',
        start: '{key} - start',
        dead: 'KONIEC GRY',
        retry: '{key} - spróbuj ponownie',
        win: 'ZWYCIĘSTWO!',
        winText: 'Wszystkie krainy oczyszczone',
        again: '{key} - zagraj ponownie',
        summary: 'Czas: {time} &nbsp; Zabójstwa: {kills} &nbsp; Złoto: {gold}',
        continueGame: '{key} - kontynuuj',
        hintBow: 'Przytrzymaj, by naciągnąć łuk, puść by strzelić',
        hintRoll: 'Podczas uniku jesteś nietykalny',
        hintShield: 'Lodowa tarcza blokuje jedno trafienie',
        hintFreeze: 'Mroźne cięcie spowalnia trafionego wroga',
        foes: 'Wrogowie: {killed}/{total}',
        gold: 'Złoto: {gold}',
        cleared: 'Droga wolna, idź w prawo >>',
        exitPrompt: 'DALEJ >>',
        shopPrompt: 'E - sklep',
        boardPrompt: 'E - zadania',
        bag: 'EKWIPUNEK',
        wear: 'Załóż',
        purchase: 'Kup',
        pack: 'Plecak',
        packEmpty: 'Plecak jest pusty',
        packFull: 'Plecak pełny!',
        quiver: 'Kołczan',
        loot: 'Łup',
        bagHint: 'Wybierz przedmiot z plecaka, by porównać go z założonym. Założony zdejmiesz jednym dotknięciem.',
        stats: 'Obrona {defense} &nbsp; Mana +{mana} &nbsp; Stamina +{stamina} &nbsp; Kryt. {crit}% &nbsp; Ciepło {warmth}',
        hintStaff: 'Przytrzymaj, by naładować lodowy pocisk',
        merchant: 'KUPIEC',
        buy: 'KUP',
        sell: 'SPRZEDAJ',
        nothingToSell: 'Nie masz nic na sprzedaż',
        quests: 'ZADANIA',
        questCollect: 'Zbierz: {item} x{count}',
        questKill: 'Pokonaj: {enemy} x{count}',
        questHint: 'Wybierz zadanie, by je przyjąć. Nagroda przyjdzie sama.',
        questDone: 'Zadanie wykonane!',
        done: 'wykonane',
        paused: 'PAUZA',
        resume: 'wznów',
        talents: 'TALENTY',
        points: 'Punkty: {points}',
        talentPoints: 'Talenty +{points}',
        talentHint: 'Wybierz kolejny węzeł, by go poznać, a poznaną umiejętność, by ją aktywować.',
        resetTalents: 'Reset talentów',
        hintTalent: 'Nowy punkt talentu! Wydaj go w talentach (T)',
        crit: 'KRYTYK!',
        btnTalents: 'TAL',
        btnBag: 'EKW',
        btnShop: 'SKLEP',
        btnQuests: 'MISJE',
        btnRoll: 'UNIK',
        btnUse: 'UŻYJ',
        btnJump: 'SKOK',
        btnFreeze: 'MRÓZ',
        btnShield: 'TARCZA',
        btnFullscreen: 'PEŁNY EKRAN',
        'stage.forest': 'Zimowy Las',
        'stage.cave': 'Lodowa Jaskinia',
        'stage.ruins': 'Ruiny Zamku',
        'enemy.wolf': 'Wilk',
        'enemy.ogre': 'Ogr',
        'enemy.archer': 'Łucznik',
        'enemy.shaman': 'Szaman',
        'enemy.alpha': 'Wilczy Alfa',
        'enemy.chief': 'Wódz ogrów',
        'enemy.mimic': 'Mimik',
        'enemy.looter': 'Szabrownik',
        'enemy.lynx': 'Śnieżny ryś',
        'enemy.poacher': 'Kłusownik',
        'item.gold': 'Złoto',
        'item.arrows': 'Strzały',
        'item.iceArrows': 'Lodowe strzały',
        'item.fireArrows': 'Płonące strzały',
        'item.pierceArrows': 'Przebijające strzały',
        'item.potion': 'Mikstura',
        'item.fur': 'Wilcze futro',
        'item.fang': 'Wilczy kieł',
        'item.sword': 'Miecz',
        'item.axe': 'Topór',
        'item.spear': 'Włócznia',
        'item.daggers': 'Sztylety',
        'item.staff': 'Kostur mrozu',
        'item.bow': 'Łuk',
        'item.shortbow': 'Krótki łuk',
        'item.helmet': 'Hełm',
        'item.hood': 'Futrzany kaptur',
        'item.armor': 'Zbroja płytowa',
        'item.chainmail': 'Kolczuga',
        'item.robe': 'Szata szronu',
        'item.cloak': 'Futrzany płaszcz',
        'item.shamanCloak': 'Płaszcz szamana',
        'item.gloves': 'Rękawice',
        'item.boots': 'Buty',
        'item.ring': 'Pierścień',
        'item.amulet': 'Amulet',
        'item.alphaFang': 'Kieł Alfy',
        'item.crown': 'Korona Wodza',
        'slot.weapon': 'broń',
        'slot.bow': 'łuk',
        'slot.head': 'głowa',
        'slot.body': 'tułów',
        'slot.back': 'plecy',
        'slot.hands': 'ręce',
        'slot.feet': 'stopy',
        'slot.ring': 'pierścień',
        'slot.neck': 'szyja',
        'stat.maxHp': '{value} zdrowia',
        'stat.maxMana': '{value} many',
        'stat.defense': '{value} obrony',
        'stat.power': '{value} obrażeń',
        'stat.spell': '{value} obrażeń czarów',
        'stat.crit': '{value} szansy na krytyk',
        'stat.lifesteal': '{value} kradzieży życia',
        'stat.manaRegen': '{value} regeneracji many',
        'stat.staminaRegen': '{value} regeneracji staminy',
        'stat.speed': '{value} szybkości ruchu',
        'stat.attackSpeed': '{value} szybkości ataku',
        'stat.grip': '{value} przyczepności na lodzie',
        'stat.warmth': '{value} ciepła',
        'stat.damage': '{value} obrażeń broni',
        'stat.reach': '{value} zasięgu',
        'stat.time': '{value}s na cios',
        'stat.stamina': '{value} staminy na cios',
        'stat.push': '{value} odrzutu',
        'stat.nova': '{value} zasięgu novy',
        'stat.draw': '{value}s naciągu',
        'stat.might': '{value} siły strzał',
        'stat.wolf': 'Co 3. trafienie przyzywa widmowego wilka',
        'stat.frenzy': '{value} obrażeń na chwilę po zabójstwie',
        'branch.warrior': 'Wojownik',
        'branch.hunter': 'Łowca',
        'branch.frost': 'Mróz',
        'talent.warrior0': '+25 zdrowia',
        'talent.warrior1': 'Miecz kradnie 20% życia',
        'talent.warrior2': 'WIR OSTRZY',
        'talent.warrior3': '+3 obrony',
        'talent.warrior4': '+4 obrażeń',
        'talent.hunter0': '+15 regeneracji staminy',
        'talent.hunter1': '50% szansy na odzysk strzały',
        'talent.hunter2': 'DESZCZ STRZAŁ',
        'talent.hunter3': 'Unik zostawia lodowy ślad',
        'talent.hunter4': '20% szansy na krytyk',
        'talent.frost0': '+25 many',
        'talent.frost1': '+12 many za zabójstwo',
        'talent.frost2': 'LODOWA NOVA',
        'talent.frost3': '+4 regeneracji many',
        'talent.frost4': '+12 obrażeń czarów',
        'skill.whirl': 'WIR',
        'skill.volley': 'SALWA',
        'skill.nova': 'NOVA',
        'speaker.hero': 'Wędrowiec',
        'speaker.merchant': 'Kupiec',
        next: '{key} - dalej',
        skip: 'ESC - pomiń',
        openSettings: '{key} - ustawienia',
        settings: 'USTAWIENIA',
        'set.graphics': 'Grafika',
        'set.game': 'Gra',
        'set.access': 'Dostępność',
        'set.keys': 'Klawisze',
        'set.save': 'Zapis',
        'set.quality': 'Jakość grafiki',
        'set.auto': 'auto',
        'set.low': 'niska',
        'set.mid': 'średnia',
        'set.high': 'wysoka',
        'set.difficulty': 'Poziom trudności',
        'set.easy': 'łatwy',
        'set.normal': 'normalny',
        'set.hard': 'trudny',
        'set.music': 'Muzyka',
        'set.effects': 'Efekty dźwiękowe',
        'set.shake': 'Drganie ekranu',
        'set.flashes': 'Błyski i efekty trafień',
        'set.bigText': 'Duży tekst',
        'set.on': 'wł.',
        'set.off': 'wył.',
        'set.keysHint': 'Wybierz akcję i naciśnij nowy klawisz. ESC anuluje. Pad działa od razu.',
        'set.export': 'Eksportuj do pliku',
        'set.import': 'Importuj z pliku',
        'set.importFailed': 'Nie udało się wczytać pliku zapisu',
        'act.left': 'W lewo',
        'act.right': 'W prawo',
        'act.jump': 'Skok',
        'act.down': 'Zeskok z platformy',
        'act.roll': 'Unik',
        'act.use': 'Użyj',
        'act.freeze': 'Mroźne cięcie',
        'act.shield': 'Lodowa tarcza',
        'act.skill': 'Umiejętność',
        'act.bag': 'Ekwipunek',
        'act.talents': 'Talenty',
        'act.talk': 'Rozmowa',
        'story.intro.0': 'Trzy zimy temu słońce po raz ostatni zaszło nad Doliną Szronu. Od tamtej nocy śnieg nie przestaje padać, a rzeki zamarzły aż do dna.',
        'story.intro.1': 'Ludzie szeptali o Zimowej Klątwie. Najdzielniejsi ruszyli na północ szukać jej źródła. Żaden nie wrócił.',
        'story.intro.2': 'Ojciec był jednym z nich. Zostawił mi tylko ten miecz i mapę z trzema znakami: las, jaskinia, ruiny.',
        'story.intro.3': 'Skoro nikt inny nie pójdzie, pójdę ja. I tym razem ktoś wróci.',
        'story.forest.0': 'Stój, wędrowcze! Dalej już tylko Zimowy Las. Wilki są tam głodniejsze niż kiedykolwiek, a ogry schodzą z gór po jedzenie.',
        'story.forest.1': 'Muszę dojść do Lodowej Jaskini. Mój ojciec szedł tą drogą.',
        'story.forest.2': 'Wielu nią szło... Watahę prowadzi Wilczy Alfa. Ma czerwone oczy, jakby sama klątwa patrzyła przez nie na świat.',
        'story.forest.3': 'Zajrzyj do mnie, zanim ruszysz dalej. A na tablicy znajdziesz prośby ludzi, którzy jeszcze się nie poddali.',
        'story.cave.0': 'Lodowa Jaskinia oddycha. Z głębin płynie ciepło, ale to nie jest ciepło ogniska.',
        'story.cave.1': 'Te kryształy... szepczą. Jakby ktoś uwięził w nich głosy.',
        'story.cave.2': 'Szamani zamrażają tu modlitwy do Zimy, każdy kryształ skrywa jedną. Rozbij ich krąg, a klątwa straci siłę. Tak mówią stare księgi.',
        'story.cave.3': 'Dość już tych modlitw.',
        'story.ruins.0': 'Zamek Szronu. Ojciec pisał, że kiedyś w tych murach płonęło sto ognisk.',
        'story.ruins.1': 'Człowieczek z mieczem! Twój ojciec też tu przyszedł. Jego tarcza wisi teraz nad moim tronem.',
        'story.ruins.2': 'W takim razie zabiorę ją do domu. Razem z twoją koroną.',
        'story.ruins.3': 'Zima dała mi tę ziemię i Zima mi jej nie odbierze. A już na pewno nie ty!',
        'story.end.0': 'Wódz padł, a śnieg wciąż pada. On nie był źródłem klątwy... tylko jej sługą.',
        'story.end.1': 'Daleko na północy, nad zamarzniętym jeziorem, Władczyni Zimy czuje śmierć swojego wasala. I pierwszy raz od trzech zim zaczyna się bać.',
        'story.end.2': 'Tarcza ojca wróci do domu. A ja pójdę dalej, na północ.',
        'intro.alpha': 'Wataha odpowiada na jego wycie',
        'intro.chief': 'Władca Ruin Zamku Szronu',
    },
    en: {
        languageName: 'English',
        language: 'Language',
        title: 'FROST BLADE',
        loading: 'Loading...',
        rotate: 'Rotate your phone',
        keysMove: 'ARROWS - move, jump and drop &nbsp; SHIFT - roll',
        keysUse: 'SPACE - use, hold with bow &nbsp; 1-9 - select',
        keysSkills: 'X - frost strike &nbsp; C - ice shield &nbsp; Q - talent skill',
        keysMenu: 'I - inventory &nbsp; T - talents &nbsp; E - merchant, quest board &nbsp; F - fullscreen &nbsp; H - photo mode &nbsp; O - settings &nbsp; ESC - pause',
        hintTouch: 'Hold USE to shoot the bow',
        goal: 'Cross the Winter Forest, the Ice Cave and the Castle Ruins',
        storyIntro: 'A Winter Curse has wrapped the land in endless frost. Find its source and end it.',
        level: 'Level {level}',
        levelUp: 'LEVEL UP! Level {level}',
        tap: 'TAP',
        start: '{key} - start',
        dead: 'GAME OVER',
        retry: '{key} - try again',
        win: 'VICTORY!',
        winText: 'All lands cleared',
        again: '{key} - play again',
        summary: 'Time: {time} &nbsp; Kills: {kills} &nbsp; Gold: {gold}',
        continueGame: '{key} - continue',
        hintBow: 'Hold to draw the bow, release to shoot',
        hintRoll: "You're untouchable while rolling",
        hintShield: 'The ice shield blocks one hit',
        hintFreeze: 'The frost strike slows the enemy it hits',
        foes: 'Enemies: {killed}/{total}',
        gold: 'Gold: {gold}',
        cleared: 'Path clear, go right >>',
        exitPrompt: 'ONWARD >>',
        shopPrompt: 'E - shop',
        boardPrompt: 'E - quests',
        bag: 'INVENTORY',
        wear: 'Wear',
        purchase: 'Buy',
        pack: 'Pack',
        packEmpty: 'The pack is empty',
        packFull: 'Pack full!',
        quiver: 'Quiver',
        loot: 'Loot',
        bagHint: 'Pick an item in the pack to compare it with the worn one. Tap a worn item to take it off.',
        stats: 'Armor {defense} &nbsp; Mana +{mana} &nbsp; Stamina +{stamina} &nbsp; Crit {crit}% &nbsp; Warmth {warmth}',
        hintStaff: 'Hold to charge an ice bolt',
        merchant: 'MERCHANT',
        buy: 'BUY',
        sell: 'SELL',
        nothingToSell: 'Nothing to sell',
        quests: 'QUESTS',
        questCollect: 'Collect: {item} x{count}',
        questKill: 'Defeat: {enemy} x{count}',
        questHint: 'Pick a quest to take it. The reward comes on its own.',
        questDone: 'Quest complete!',
        done: 'done',
        paused: 'PAUSED',
        resume: 'resume',
        talents: 'TALENTS',
        points: 'Points: {points}',
        talentPoints: 'Talents +{points}',
        talentHint: 'Pick the next node to learn it, or a learned skill to make it active.',
        resetTalents: 'Reset talents',
        hintTalent: 'New talent point! Spend it in talents (T)',
        crit: 'CRIT!',
        btnTalents: 'TAL',
        btnBag: 'BAG',
        btnShop: 'SHOP',
        btnQuests: 'QUESTS',
        btnRoll: 'ROLL',
        btnUse: 'USE',
        btnJump: 'JUMP',
        btnFreeze: 'FROST',
        btnShield: 'SHIELD',
        btnFullscreen: 'FULLSCREEN',
        'stage.forest': 'Winter Forest',
        'stage.cave': 'Ice Cave',
        'stage.ruins': 'Castle Ruins',
        'enemy.wolf': 'Wolf',
        'enemy.ogre': 'Ogre',
        'enemy.archer': 'Archer',
        'enemy.shaman': 'Shaman',
        'enemy.alpha': 'Alpha Wolf',
        'enemy.chief': 'Ogre Chief',
        'enemy.mimic': 'Mimic',
        'enemy.looter': 'Looter',
        'enemy.lynx': 'Snow Lynx',
        'enemy.poacher': 'Poacher',
        'item.gold': 'Gold',
        'item.arrows': 'Arrows',
        'item.iceArrows': 'Ice arrows',
        'item.fireArrows': 'Fire arrows',
        'item.pierceArrows': 'Piercing arrows',
        'item.potion': 'Potion',
        'item.fur': 'Wolf fur',
        'item.fang': 'Wolf fang',
        'item.sword': 'Sword',
        'item.axe': 'Axe',
        'item.spear': 'Spear',
        'item.daggers': 'Daggers',
        'item.staff': 'Frost staff',
        'item.bow': 'Bow',
        'item.shortbow': 'Short bow',
        'item.helmet': 'Helmet',
        'item.hood': 'Fur hood',
        'item.armor': 'Plate armor',
        'item.chainmail': 'Chainmail',
        'item.robe': 'Frost robe',
        'item.cloak': 'Fur cloak',
        'item.shamanCloak': 'Shaman cloak',
        'item.gloves': 'Gloves',
        'item.boots': 'Boots',
        'item.ring': 'Ring',
        'item.amulet': 'Amulet',
        'item.alphaFang': 'Alpha Fang',
        'item.crown': "Chief's Crown",
        'slot.weapon': 'weapon',
        'slot.bow': 'bow',
        'slot.head': 'head',
        'slot.body': 'body',
        'slot.back': 'back',
        'slot.hands': 'hands',
        'slot.feet': 'feet',
        'slot.ring': 'ring',
        'slot.neck': 'neck',
        'stat.maxHp': '{value} health',
        'stat.maxMana': '{value} mana',
        'stat.defense': '{value} armor',
        'stat.power': '{value} damage',
        'stat.spell': '{value} spell damage',
        'stat.crit': '{value} critical chance',
        'stat.lifesteal': '{value} life steal',
        'stat.manaRegen': '{value} mana regen',
        'stat.staminaRegen': '{value} stamina regen',
        'stat.speed': '{value} move speed',
        'stat.attackSpeed': '{value} attack speed',
        'stat.grip': '{value} grip on ice',
        'stat.warmth': '{value} warmth',
        'stat.damage': '{value} weapon damage',
        'stat.reach': '{value} reach',
        'stat.time': '{value}s per swing',
        'stat.stamina': '{value} stamina per swing',
        'stat.push': '{value} knockback',
        'stat.nova': '{value} nova radius',
        'stat.draw': '{value}s draw time',
        'stat.might': '{value} arrow power',
        'stat.wolf': 'Every 3rd hit calls a spirit wolf',
        'stat.frenzy': '{value} damage for a while after a kill',
        'branch.warrior': 'Warrior',
        'branch.hunter': 'Hunter',
        'branch.frost': 'Frost',
        'talent.warrior0': '+25 health',
        'talent.warrior1': 'Sword steals 20% life',
        'talent.warrior2': 'BLADE WHIRL',
        'talent.warrior3': '+3 armor',
        'talent.warrior4': '+4 damage',
        'talent.hunter0': '+15 stamina regen',
        'talent.hunter1': '50% chance to recover arrows',
        'talent.hunter2': 'ARROW RAIN',
        'talent.hunter3': 'Rolls leave an ice trail',
        'talent.hunter4': '20% critical chance',
        'talent.frost0': '+25 mana',
        'talent.frost1': '+12 mana per kill',
        'talent.frost2': 'ICE NOVA',
        'talent.frost3': '+4 mana regen',
        'talent.frost4': '+12 spell damage',
        'skill.whirl': 'WHIRL',
        'skill.volley': 'RAIN',
        'skill.nova': 'NOVA',
        'speaker.hero': 'Wanderer',
        'speaker.merchant': 'Merchant',
        next: '{key} - continue',
        skip: 'ESC - skip',
        openSettings: '{key} - settings',
        settings: 'SETTINGS',
        'set.graphics': 'Graphics',
        'set.game': 'Game',
        'set.access': 'Accessibility',
        'set.keys': 'Keys',
        'set.save': 'Save',
        'set.quality': 'Graphics quality',
        'set.auto': 'auto',
        'set.low': 'low',
        'set.mid': 'medium',
        'set.high': 'high',
        'set.difficulty': 'Difficulty',
        'set.easy': 'easy',
        'set.normal': 'normal',
        'set.hard': 'hard',
        'set.music': 'Music',
        'set.effects': 'Sound effects',
        'set.shake': 'Screen shake',
        'set.flashes': 'Flashes and hit effects',
        'set.bigText': 'Big text',
        'set.on': 'on',
        'set.off': 'off',
        'set.keysHint': 'Pick an action and press a new key. ESC cancels. Gamepads work right away.',
        'set.export': 'Export to file',
        'set.import': 'Import from file',
        'set.importFailed': 'Could not read the save file',
        'act.left': 'Left',
        'act.right': 'Right',
        'act.jump': 'Jump',
        'act.down': 'Drop from platform',
        'act.roll': 'Roll',
        'act.use': 'Use',
        'act.freeze': 'Frost strike',
        'act.shield': 'Ice shield',
        'act.skill': 'Skill',
        'act.bag': 'Inventory',
        'act.talents': 'Talents',
        'act.talk': 'Talk',
        'story.intro.0': 'Three winters ago the sun set over the Frost Valley for the last time. Since that night the snow has never stopped and the rivers have frozen to their beds.',
        'story.intro.1': 'People whispered of a Winter Curse. The bravest went north to find its source. None came back.',
        'story.intro.2': 'My father was one of them. All he left me was this sword and a map with three marks: a forest, a cave, ruins.',
        'story.intro.3': 'If no one else will go, I will. And this time someone will come back.',
        'story.forest.0': "Hold, wanderer! Past here there's only the Winter Forest. The wolves are hungrier than ever and ogres come down from the mountains to feed.",
        'story.forest.1': 'I have to reach the Ice Cave. My father walked this road.',
        'story.forest.2': 'Many walked it... The pack follows the Alpha Wolf. Its eyes burn red, as if the curse itself looked out through them.',
        'story.forest.3': "See my wares before you go. And the board holds requests from folk who haven't given up yet.",
        'story.cave.0': 'The Ice Cave breathes. Warmth rises from the depths, but it is not the warmth of a fire.',
        'story.cave.1': 'These crystals... they whisper. As if someone had trapped voices inside them.',
        'story.cave.2': 'The shamans freeze their prayers to Winter here, every crystal holds one. Break their circle and the curse weakens. So say the old books.',
        'story.cave.3': 'Enough prayers.',
        'story.ruins.0': 'Frost Castle. Father wrote that a hundred fires once burned within these walls.',
        'story.ruins.1': 'A little man with a sword! Your father came here too. His shield hangs over my throne now.',
        'story.ruins.2': 'Then I will take it home. Along with your crown.',
        'story.ruins.3': 'Winter gave me this land and Winter will not take it back. Least of all through you!',
        'story.end.0': "The Chief has fallen, yet the snow still falls. He wasn't the source of the curse... only its servant.",
        'story.end.1': 'Far to the north, above a frozen lake, the Winter Queen feels her vassal die. And for the first time in three winters, she is afraid.',
        'story.end.2': "Father's shield will go home. And I am going further north.",
        'intro.alpha': 'The pack answers its howl',
        'intro.chief': 'Lord of the Frost Castle Ruins',
    },
}

function saved() {
    try {
        return localStorage.getItem('language')
    } catch {
        return null
    }
}

let current = [saved(), navigator.language.slice(0, 2)].find(code => code in TEXTS) ?? 'en'

export const LANGUAGES = Object.keys(TEXTS)
export const language = () => current
export const languageName = code => TEXTS[code].languageName

// Text as HTML with {name} placeholders filled from values. Missing texts fall back to English.
export function t(key, values = {}) {
    return (TEXTS[current][key] ?? TEXTS.en[key]).replace(/\{(\w+)\}/g, (_, name) => values[name])
}

// Fills every element marked with data-text
export function translatePage() {
    document.documentElement.lang = current
    for (const element of document.querySelectorAll('[data-text]')) element.innerHTML = t(element.dataset.text)
}

export function setLanguage(code) {
    current = code
    try {
        localStorage.setItem('language', code)
    } catch { }
    translatePage()
}
