// Texts shown to the player. To add a language copy one block under a new code and translate the values.
const TEXTS = {
    pl: {
        languageName: 'Polski',
        language: 'Język',
        title: 'MROŹNE OSTRZE',
        loading: 'Ładowanie...',
        rotate: 'Obróć telefon poziomo',
        keysMove: 'STRZAŁKI - ruch i skok &nbsp; SHIFT - unik',
        keysUse: 'SPACJA - użyj, przytrzymaj z łukiem &nbsp; 1-9 - wybór',
        keysSkills: 'X - mroźne cięcie &nbsp; C - lodowa tarcza &nbsp; Q - umiejętność z talentów',
        keysMenu: 'I - ekwipunek &nbsp; T - talenty &nbsp; E - kupiec, tablica zadań &nbsp; F - pełny ekran &nbsp; H - tryb foto &nbsp; ESC - pauza',
        hintTouch: 'Przytrzymaj UŻYJ, by strzelić z łuku',
        goal: 'Przejdź Zimowy Las, Lodową Jaskinię i Ruiny Zamku',
        storyIntro: 'Zimowa Klątwa spowiła krainę wiecznym mrozem. Odnajdź jej źródło i połóż jej kres.',
        'story.forest': 'Wilki i ogry strzegą zamarzniętego lasu na granicy krainy.',
        'story.cave': 'Głęboko w Lodowej Jaskini szamani karmią klątwę swoją magią.',
        'story.ruins': 'W Ruinach Zamku czeka Wódz Ogrów, władca tej zmarzniętej ziemi.',
        level: 'Poziom {level}',
        levelUp: 'AWANS! Poziom {level}',
        tap: 'DOTKNIJ',
        start: '{key} - start',
        dead: 'KONIEC GRY',
        retry: '{key} - spróbuj ponownie',
        win: 'ZWYCIĘSTWO!',
        winText: 'Wszystkie krainy oczyszczone',
        again: '{key} - zagraj ponownie',
        summary: 'Czas: {time} &nbsp; Zabójstwa: {kills} &nbsp; Złoto: {gold}',
        continueGame: '{key} - kontynuuj',
        hintBow: 'Przytrzymaj, by naciągnąć łuk, puść by strzelić',
        hintRoll: 'Podczas uniku jesteś nietykalny',
        hintShield: 'Lodowa tarcza blokuje jedno trafienie',
        hintFreeze: 'Mroźne cięcie spowalnia trafionego wroga',
        foes: 'Wrogowie: {killed}/{total}',
        gold: 'Złoto: {gold}',
        cleared: 'Droga wolna, idź w prawo >>',
        exitPrompt: 'DALEJ >>',
        shopPrompt: 'E - sklep',
        boardPrompt: 'E - zadania',
        bag: 'EKWIPUNEK',
        wear: 'Załóż',
        purchase: 'Kup',
        pack: 'Plecak',
        packEmpty: 'Plecak jest pusty',
        packFull: 'Plecak pełny!',
        quiver: 'Kołczan',
        loot: 'Łup',
        bagHint: 'Wybierz przedmiot z plecaka, by porównać go z założonym. Założony zdejmiesz jednym dotknięciem.',
        stats: 'Obrona {defense} &nbsp; Mana +{mana} &nbsp; Stamina +{stamina} &nbsp; Kryt. {crit}% &nbsp; Ciepło {warmth}',
        hintStaff: 'Przytrzymaj, by naładować lodowy pocisk',
        merchant: 'KUPIEC',
        buy: 'KUP',
        sell: 'SPRZEDAJ',
        nothingToSell: 'Nie masz nic na sprzedaż',
        quests: 'ZADANIA',
        questCollect: 'Zbierz: {item} x{count}',
        questKill: 'Pokonaj: {enemy} x{count}',
        questHint: 'Wybierz zadanie, by je przyjąć. Nagroda przyjdzie sama.',
        questDone: 'Zadanie wykonane!',
        done: 'wykonane',
        paused: 'PAUZA',
        resume: 'wznów',
        talents: 'TALENTY',
        points: 'Punkty: {points}',
        talentPoints: 'Talenty +{points}',
        talentHint: 'Wybierz kolejny węzeł, by go poznać, a poznaną umiejętność, by ją aktywować.',
        resetTalents: 'Reset talentów',
        hintTalent: 'Nowy punkt talentu! Wydaj go w talentach (T)',
        crit: 'KRYTYK!',
        btnTalents: 'TAL',
        btnBag: 'EKW',
        btnShop: 'SKLEP',
        btnQuests: 'MISJE',
        btnRoll: 'UNIK',
        btnUse: 'UŻYJ',
        btnJump: 'SKOK',
        btnFreeze: 'MRÓZ',
        btnShield: 'TARCZA',
        btnFullscreen: 'PEŁNY EKRAN',
        'stage.forest': 'Zimowy Las',
        'stage.cave': 'Lodowa Jaskinia',
        'stage.ruins': 'Ruiny Zamku',
        'enemy.wolf': 'Wilk',
        'enemy.ogre': 'Ogr',
        'enemy.archer': 'Łucznik',
        'enemy.shaman': 'Szaman',
        'enemy.alpha': 'Wilczy Alfa',
        'enemy.chief': 'Wódz ogrów',
        'enemy.mimic': 'Mimik',
        'enemy.looter': 'Szabrownik',
        'enemy.lynx': 'Śnieżny ryś',
        'enemy.poacher': 'Kłusownik',
        'item.gold': 'Złoto',
        'item.arrows': 'Strzały',
        'item.iceArrows': 'Lodowe strzały',
        'item.fireArrows': 'Płonące strzały',
        'item.pierceArrows': 'Przebijające strzały',
        'item.potion': 'Mikstura',
        'item.fur': 'Wilcze futro',
        'item.fang': 'Wilczy kieł',
        'item.sword': 'Miecz',
        'item.axe': 'Topór',
        'item.spear': 'Włócznia',
        'item.daggers': 'Sztylety',
        'item.staff': 'Kostur mrozu',
        'item.bow': 'Łuk',
        'item.shortbow': 'Krótki łuk',
        'item.helmet': 'Hełm',
        'item.hood': 'Futrzany kaptur',
        'item.armor': 'Zbroja płytowa',
        'item.chainmail': 'Kolczuga',
        'item.robe': 'Szata szronu',
        'item.cloak': 'Futrzany płaszcz',
        'item.shamanCloak': 'Płaszcz szamana',
        'item.gloves': 'Rękawice',
        'item.boots': 'Buty',
        'item.ring': 'Pierścień',
        'item.amulet': 'Amulet',
        'item.alphaFang': 'Kieł Alfy',
        'item.crown': 'Korona Wodza',
        'slot.weapon': 'broń',
        'slot.bow': 'łuk',
        'slot.head': 'głowa',
        'slot.body': 'tułów',
        'slot.back': 'plecy',
        'slot.hands': 'ręce',
        'slot.feet': 'stopy',
        'slot.ring': 'pierścień',
        'slot.neck': 'szyja',
        'stat.maxHp': '{value} zdrowia',
        'stat.maxMana': '{value} many',
        'stat.defense': '{value} obrony',
        'stat.power': '{value} obrażeń',
        'stat.spell': '{value} obrażeń czarów',
        'stat.crit': '{value} szansy na krytyk',
        'stat.lifesteal': '{value} kradzieży życia',
        'stat.manaRegen': '{value} regeneracji many',
        'stat.staminaRegen': '{value} regeneracji staminy',
        'stat.speed': '{value} szybkości ruchu',
        'stat.attackSpeed': '{value} szybkości ataku',
        'stat.grip': '{value} przyczepności na lodzie',
        'stat.warmth': '{value} ciepła',
        'stat.damage': '{value} obrażeń broni',
        'stat.reach': '{value} zasięgu',
        'stat.time': '{value}s na cios',
        'stat.stamina': '{value} staminy na cios',
        'stat.push': '{value} odrzutu',
        'stat.nova': '{value} zasięgu novy',
        'stat.draw': '{value}s naciągu',
        'stat.might': '{value} siły strzał',
        'stat.wolf': 'Co 3. trafienie przyzywa widmowego wilka',
        'stat.frenzy': '{value} obrażeń na chwilę po zabójstwie',
        'branch.warrior': 'Wojownik',
        'branch.hunter': 'Łowca',
        'branch.frost': 'Mróz',
        'talent.warrior0': '+25 zdrowia',
        'talent.warrior1': 'Miecz kradnie 20% życia',
        'talent.warrior2': 'WIR OSTRZY',
        'talent.warrior3': '+3 obrony',
        'talent.warrior4': '+4 obrażeń',
        'talent.hunter0': '+15 regeneracji staminy',
        'talent.hunter1': '50% szansy na odzysk strzały',
        'talent.hunter2': 'DESZCZ STRZAŁ',
        'talent.hunter3': 'Unik zostawia lodowy ślad',
        'talent.hunter4': '20% szansy na krytyk',
        'talent.frost0': '+25 many',
        'talent.frost1': '+12 many za zabójstwo',
        'talent.frost2': 'LODOWA NOVA',
        'talent.frost3': '+4 regeneracji many',
        'talent.frost4': '+12 obrażeń czarów',
        'skill.whirl': 'WIR',
        'skill.volley': 'SALWA',
        'skill.nova': 'NOVA',
    },
    en: {
        languageName: 'English',
        language: 'Language',
        title: 'FROST BLADE',
        loading: 'Loading...',
        rotate: 'Rotate your phone',
        keysMove: 'ARROWS - move and jump &nbsp; SHIFT - roll',
        keysUse: 'SPACE - use, hold with bow &nbsp; 1-9 - select',
        keysSkills: 'X - frost strike &nbsp; C - ice shield &nbsp; Q - talent skill',
        keysMenu: 'I - inventory &nbsp; T - talents &nbsp; E - merchant, quest board &nbsp; F - fullscreen &nbsp; H - photo mode &nbsp; ESC - pause',
        hintTouch: 'Hold USE to shoot the bow',
        goal: 'Cross the Winter Forest, the Ice Cave and the Castle Ruins',
        storyIntro: 'A Winter Curse has wrapped the land in endless frost. Find its source and end it.',
        'story.forest': 'Wolves and ogres guard the frozen forest at the border of the land.',
        'story.cave': 'Deep in the Ice Cave, shamans feed the curse with their magic.',
        'story.ruins': 'In the Castle Ruins waits the Ogre Chief, lord of this frozen land.',
        level: 'Level {level}',
        levelUp: 'LEVEL UP! Level {level}',
        tap: 'TAP',
        start: '{key} - start',
        dead: 'GAME OVER',
        retry: '{key} - try again',
        win: 'VICTORY!',
        winText: 'All lands cleared',
        again: '{key} - play again',
        summary: 'Time: {time} &nbsp; Kills: {kills} &nbsp; Gold: {gold}',
        continueGame: '{key} - continue',
        hintBow: 'Hold to draw the bow, release to shoot',
        hintRoll: "You're untouchable while rolling",
        hintShield: 'The ice shield blocks one hit',
        hintFreeze: 'The frost strike slows the enemy it hits',
        foes: 'Enemies: {killed}/{total}',
        gold: 'Gold: {gold}',
        cleared: 'Path clear, go right >>',
        exitPrompt: 'ONWARD >>',
        shopPrompt: 'E - shop',
        boardPrompt: 'E - quests',
        bag: 'INVENTORY',
        wear: 'Wear',
        purchase: 'Buy',
        pack: 'Pack',
        packEmpty: 'The pack is empty',
        packFull: 'Pack full!',
        quiver: 'Quiver',
        loot: 'Loot',
        bagHint: 'Pick an item in the pack to compare it with the worn one. Tap a worn item to take it off.',
        stats: 'Armor {defense} &nbsp; Mana +{mana} &nbsp; Stamina +{stamina} &nbsp; Crit {crit}% &nbsp; Warmth {warmth}',
        hintStaff: 'Hold to charge an ice bolt',
        merchant: 'MERCHANT',
        buy: 'BUY',
        sell: 'SELL',
        nothingToSell: 'Nothing to sell',
        quests: 'QUESTS',
        questCollect: 'Collect: {item} x{count}',
        questKill: 'Defeat: {enemy} x{count}',
        questHint: 'Pick a quest to take it. The reward comes on its own.',
        questDone: 'Quest complete!',
        done: 'done',
        paused: 'PAUSED',
        resume: 'resume',
        talents: 'TALENTS',
        points: 'Points: {points}',
        talentPoints: 'Talents +{points}',
        talentHint: 'Pick the next node to learn it, or a learned skill to make it active.',
        resetTalents: 'Reset talents',
        hintTalent: 'New talent point! Spend it in talents (T)',
        crit: 'CRIT!',
        btnTalents: 'TAL',
        btnBag: 'BAG',
        btnShop: 'SHOP',
        btnQuests: 'QUESTS',
        btnRoll: 'ROLL',
        btnUse: 'USE',
        btnJump: 'JUMP',
        btnFreeze: 'FROST',
        btnShield: 'SHIELD',
        btnFullscreen: 'FULLSCREEN',
        'stage.forest': 'Winter Forest',
        'stage.cave': 'Ice Cave',
        'stage.ruins': 'Castle Ruins',
        'enemy.wolf': 'Wolf',
        'enemy.ogre': 'Ogre',
        'enemy.archer': 'Archer',
        'enemy.shaman': 'Shaman',
        'enemy.alpha': 'Alpha Wolf',
        'enemy.chief': 'Ogre Chief',
        'enemy.mimic': 'Mimic',
        'enemy.looter': 'Looter',
        'enemy.lynx': 'Snow Lynx',
        'enemy.poacher': 'Poacher',
        'item.gold': 'Gold',
        'item.arrows': 'Arrows',
        'item.iceArrows': 'Ice arrows',
        'item.fireArrows': 'Fire arrows',
        'item.pierceArrows': 'Piercing arrows',
        'item.potion': 'Potion',
        'item.fur': 'Wolf fur',
        'item.fang': 'Wolf fang',
        'item.sword': 'Sword',
        'item.axe': 'Axe',
        'item.spear': 'Spear',
        'item.daggers': 'Daggers',
        'item.staff': 'Frost staff',
        'item.bow': 'Bow',
        'item.shortbow': 'Short bow',
        'item.helmet': 'Helmet',
        'item.hood': 'Fur hood',
        'item.armor': 'Plate armor',
        'item.chainmail': 'Chainmail',
        'item.robe': 'Frost robe',
        'item.cloak': 'Fur cloak',
        'item.shamanCloak': 'Shaman cloak',
        'item.gloves': 'Gloves',
        'item.boots': 'Boots',
        'item.ring': 'Ring',
        'item.amulet': 'Amulet',
        'item.alphaFang': 'Alpha Fang',
        'item.crown': "Chief's Crown",
        'slot.weapon': 'weapon',
        'slot.bow': 'bow',
        'slot.head': 'head',
        'slot.body': 'body',
        'slot.back': 'back',
        'slot.hands': 'hands',
        'slot.feet': 'feet',
        'slot.ring': 'ring',
        'slot.neck': 'neck',
        'stat.maxHp': '{value} health',
        'stat.maxMana': '{value} mana',
        'stat.defense': '{value} armor',
        'stat.power': '{value} damage',
        'stat.spell': '{value} spell damage',
        'stat.crit': '{value} critical chance',
        'stat.lifesteal': '{value} life steal',
        'stat.manaRegen': '{value} mana regen',
        'stat.staminaRegen': '{value} stamina regen',
        'stat.speed': '{value} move speed',
        'stat.attackSpeed': '{value} attack speed',
        'stat.grip': '{value} grip on ice',
        'stat.warmth': '{value} warmth',
        'stat.damage': '{value} weapon damage',
        'stat.reach': '{value} reach',
        'stat.time': '{value}s per swing',
        'stat.stamina': '{value} stamina per swing',
        'stat.push': '{value} knockback',
        'stat.nova': '{value} nova radius',
        'stat.draw': '{value}s draw time',
        'stat.might': '{value} arrow power',
        'stat.wolf': 'Every 3rd hit calls a spirit wolf',
        'stat.frenzy': '{value} damage for a while after a kill',
        'branch.warrior': 'Warrior',
        'branch.hunter': 'Hunter',
        'branch.frost': 'Frost',
        'talent.warrior0': '+25 health',
        'talent.warrior1': 'Sword steals 20% life',
        'talent.warrior2': 'BLADE WHIRL',
        'talent.warrior3': '+3 armor',
        'talent.warrior4': '+4 damage',
        'talent.hunter0': '+15 stamina regen',
        'talent.hunter1': '50% chance to recover arrows',
        'talent.hunter2': 'ARROW RAIN',
        'talent.hunter3': 'Rolls leave an ice trail',
        'talent.hunter4': '20% critical chance',
        'talent.frost0': '+25 mana',
        'talent.frost1': '+12 mana per kill',
        'talent.frost2': 'ICE NOVA',
        'talent.frost3': '+4 mana regen',
        'talent.frost4': '+12 spell damage',
        'skill.whirl': 'WHIRL',
        'skill.volley': 'RAIN',
        'skill.nova': 'NOVA',
    },
}

function saved() {
    try {
        return localStorage.getItem('language')
    } catch {
        return null
    }
}

let current = [saved(), navigator.language.slice(0, 2)].find(code => code in TEXTS) ?? 'en'

export const LANGUAGES = Object.keys(TEXTS)
export const language = () => current
export const languageName = code => TEXTS[code].languageName

// Text as HTML with {name} placeholders filled from values. Missing texts fall back to English.
export function t(key, values = {}) {
    return (TEXTS[current][key] ?? TEXTS.en[key]).replace(/\{(\w+)\}/g, (_, name) => values[name])
}

// Fills every element marked with data-text
export function translatePage() {
    document.documentElement.lang = current
    for (const element of document.querySelectorAll('[data-text]')) element.innerHTML = t(element.dataset.text)
}

export function setLanguage(code) {
    current = code
    try {
        localStorage.setItem('language', code)
    } catch { }
    translatePage()
}
